### ISSUE TITLE
Gravatars with a checkbox

### ISSUE THREAD

**Issue by dertuxmalwieder** [posativ/isso#141]
> (Cthulhux) gravatar evtl mit checkbox "nutze gravatar"
> (Cthulhux) ansonsten.. wer datenschutz will, hat eh kein gravatar^^
> (Cthulhux) mit checkbox würds gehen. angekreuzt = md5(Email) -> <img src="http://www.gravatar..."usw>, nicht angekreuzt = lokales bild

**Comment by JohnMaguire** [comment]
Hi, is there any chance you could explain what this issue says in English? I'm interested in using isso on my website, and was looking for Gravatar support. I may submit a pull request soon here, but was wondering what the "checkbox" bit was about.

**Comment by georg90** [comment]
I'd love that option!

If someone can point me to the right files where the avatar is generated, I could try to implement something.

**Comment by JohnMaguire** [comment]
I believe to add a Gravatar, you'd need to modify this template: https://github.com/posativ/isso/blob/master/isso/js/app/text/comment.jade#L2-L4

Seems like you would need to add an option to the Isso client JS to use Gravatar (so you could set it while embedding the comments). If the option is set, simply [MD5 the trimmed, lowercase email](https://en.gravatar.com/site/implement/images/) and create an img tag linking to Gravatar.

To add support for Gravatars even while the hashing config is enabled, I think you'd have to add an MD5 hash to the output here: https://github.com/posativ/isso/blob/5d21e1b20a95d9744425b41e104a71f446fcc315/isso/views/comments.py#L426-L445

**Comment by JohnMaguire** [comment]
@posativ Could you comment whether the above is accurate? I'm interested in possibly implementing this feature if nobody else does.

**Comment by georg90** [comment]
+1 if you do.
I'm currently traveling SEA so I can't really work on this myself..

**Comment by loggerhead** [comment]
This feature would be useful to identify user by human eye.

**Comment by benjhess** [comment]
I just implemented this feature and made a [pull request](https://github.com/posativ/isso/pull/317). 
@posativ It would be nice if you could find the time to take a look at it and give some feedback :)

**Comment by pozitron57** [comment]
@benjhess You could check [FAQ](https://posativ.org/isso/faq/) for the posativ's opinion on the gravatar.

**Comment by benjhess** [comment]
@pozitron57 I know about the opinion. Thats why it is implemented as an **opt-in feature**.  You don't have to use it but you can. And also i don't see any problem with gravatar regarding privacy. If someone does not want to use gravatar then this person simply does not need to create such an account. The mail address is also not shared with gravatar. Its just a md5 hash what you use to request an avatar image from gravatar...

**Comment by pozitron57** [comment]
What you are saying is quite reasonable to me, I just wanted to make sure that you've read the FAQ.

**Comment by skorokithakis** [comment]
A better idea would be to add a configurable avatar url.

For example, configuration should look like:

~~~
avatar_url=https://secure.gravatar.com/avatar/{hash}.jpg
~~~

Isso would then replace `{hash}` with each user's email hash, as specified in the hashing section. This would allow people to use any service they wanted, instead of just Gravatar.

**Comment by madranet** [comment]
i'd like to see something like this implemented too.  

I'm don't really see where @posativ is coming from with his trenchant opposition to Avatars / Gravatars / <whatever>Atars.  I know he cites reasons of anonymity but, for my use case, anonymity was not the main reason for choosing Isso. I use it because it's a way of taking back control of my own comments from data harvesters like Disqus. 

At the very least, I'd like to see an option for the site owner to have a custom avatar.  This would let people see where and when the original writer of an article was participating in the comments.

**Comment by blatinier** [comment]
Merged opt-in gravatar support
