### ISSUE TITLE
[support] how can I get a recent comments page?

### ISSUE THREAD

**Issue by ghost** [posativ/isso#234]
I would like to have a recent comments page: a page where the author and the page in which he/she made a comment are displayed. Like this
![captura_2016-02-21_11-47-53](https://cloud.githubusercontent.com/assets/89915/13202180/1f839602-d891-11e5-983c-3763cfa247ee.png)

Is it possible to do with isso?

**Comment by blatinier** [comment]
Not yet, but the admin interface might provide this in the end (issue #10 ). See the first shot at it (PR #256 ), it might give you statisfaction.

**Comment by wzpan** [comment]
Need this feature too!

**Comment by somenxavier** [comment]
I could offer $15 reward for that. It's seems very obvious of implement it

**Comment by wzpan** [comment]
@somenxavier FYI, I wrote a comment system in pure JS. It's based on Github issue and doesn't not require a server. Since it's written in pure JS, you can easily port it to any static blog.

How it looks like:

![2017-07-01 23-28-47](https://user-images.githubusercontent.com/1631405/27763367-1375aa48-5eb5-11e7-8adf-21997f6c5722.png)

Recent comment list is also supported:

![2017-07-01 22-25-35](https://user-images.githubusercontent.com/1631405/27763360-f2655a06-5eb4-11e7-8313-6d9cbe2477f6.png)

You can try it at [my blog](http://hahack.com). If you are interested at this project, please [watch it](https://github.com/wzpan/hexo-github-comment). It will soon be opened source.

**Comment by blatinier** [comment]
@wzpan It's not really helping with the issue to suggest a switch to another system…
Moreover, one of the key point of isso is the self-hosting part and being non dependant on tiers. You could also just use Disqus in this case…

**Comment by wzpan** [comment]
@blatinier Disqus is not accessible in our country, sadly...

**Comment by Konzertheld** [comment]
Relates to #556

**Comment by ix5** [comment]
Can be implemented using https://github.com/posativ/isso/pull/610 and a bit of glue code.
This feature request as-is should be outside Isso's purview.
