### ISSUE TITLE
override thread discovery with custom data-attributes

### ISSUE THREAD

**Issue by posativ** [posativ/isso#27]

**Comment by dashohoxha** [comment]
This is a big problem for me, because I want to use comments in a mobile app, where url almost never changes, but the content changes (through ajax). So, I need to be able to reference the comments by id, not by url.

Without knowing the structure of the DB and without looking at the code, I would suggest to just get rid of URLs everywhere. We don't need them, we need just IDs in order to identify comment threads. By ID I mean a unique string, not a number. In special cases it can be set to be the url itself, in special cases it can be a number (converted to string), but let the website decide what the ID of the comment thread should be.

**Comment by postblue** [comment]
It was working with 0.9.10, but since 0.10.1 it seems not, too bad!

**Comment by posativ** [comment]
What's the output of `pip --version`?

**Comment by posativ** [comment]
This issue is still open, what do you mean exactly?

**Comment by blatinier** [comment]
This should be closed since you merged #252 right?

**Comment by rawsh** [comment]
Can this be used now? AMP pages are a usecase

**Comment by ix5** [comment]
Should be fixed by #252
