### ISSUE TITLE
Error: call to eval() blocked by CSP

### ISSUE THREAD

**Issue by athoune** [posativ/isso#274]
It happens when the website use strict HSTS headers.

**Comment by posativ** [comment]
Yup, found the same behavior last week when I applied random security headers.

**Comment by athoune** [comment]
I don't understand the eval trick, "js" is already a function. Why do you a back flip followed by a front flip?

**Comment by posativ** [comment]
JavaScript development sucks?

**Comment by athoune** [comment]
Sure, but Isso is a great product, the perfect sidekick for static website.

Here is the context for my question : https://github.com/posativ/isso/blob/b5e7c78dcccbd99cbdd676ba84397fba3348a452/isso/js/app/jade.js#L9-L11

**Comment by mdosch** [comment]
May this be useful? https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/eval

I tried a little bit to replace the eval, but wasn't succesful so far. No wonder, as I'm no programmer and so it's just trial and error.

**Comment by posativ** [comment]
It will not work without, due to the embedded template with executable code. A different approach for templates is needed.

**Comment by Libbum** [comment]
Just to add this discussion: the specific header that's causing the problem here is the `Content Security Policy` (CSP), not HSTS. Users must add `unsafe-eval` to the `script-src` portion of their CSP policy. This is considered quite a harmful action, which drops your security score by 15 points on the [Mozilla Observatory](https://observatory.mozilla.org) tests.

I've only just moved across to isso from Disqus, so don't have an answer to this issue just yet, but I'll certainly look into it - I think this task should be set to quite a high priority.

**Comment by mdosch** [comment]
Is anyone having an idea about a possible solution? As the isso js is the only script on my website it isn't really unsafe to have "unsafe-eval" in CSP but also it doesn't really look good and it is a principle of mine to try to configure my website as safe as possible.

@Libbum the Observatory actually dropped my rating now from A to B+ by -20 points due to unsafe CSP implementation. I think this very confusing as they should consider I load only one script from my own host and not potential malicous stuff from Google, Facebook or other Tracking-companies.

**Comment by Libbum** [comment]
@mdosch, as posativ has stated, the issue is with the way templating is handled. Isso is using an old version of Pug (which used to be called Jade) and is quite embedded into the code. I attempted to upgrade to the latest Pug version to attempt a fix, but never managed to get there. I'm not even sure that will fix the problem anyway. Templating is a tough job and removing it entirely would just make the code uglier and more difficult regardless. So for the moment I'm at a loss on how to proceed.

I agree with your sentiment and principles though and it really irks me to have this policy running. So I'm actively working on [something new](https://github.com/Libbum/oration) as a personal project to learn Elm and work with Rocket. No where near done and I'm not sure if it ever will be, but keep an eye on it as a possible future solution.

**Comment by vincentbernat** [comment]
I am not familiar with this templating system. Wouldn't it be possible to precompile the functions and skip the eval step? The eval step could stay during development but would go away in the minimal version.
