### ISSUE TITLE
Cannot reply as long as my first post can still be edited

### ISSUE THREAD

**Issue by mdosch** [posativ/isso#342]
Steps to reproduce:

- Isso is configured to allow you to edit your comments for some time (e.g. 15 minutes)
- Post a comment in Browser#1 
- Post a comment via button reply in Browser#2
- Reload in Browser#1 (The new comment is shown, on your first comment you still have "edit" and "delete" possibility)
- Reply to comment made from Browser#2
- Send button doesn't work

Remarks: 
All the comments were done without filling in name, email or homepage.
Browser: Firefox ESR 52.3.0 (64-bit) on debian stretch

**Comment by dertuxmalwieder** [comment]
Confirmed, by the way.

**Comment by ix5** [comment]
With current moderation tools (`[guard]`) changes, is this still a pressing issue?

**Comment by mdosch** [comment]
I just checked and you still can't comment while you are allowed to edit your first comment. I am not sure how `[guard]` shall be related.

**Comment by ix5** [comment]
What you're looking at is a spam prevention measure by isso. See the explanation for the `[guard]` section in isso's documentation here:
https://github.com/posativ/isso/blob/be538a2abbaa1e1ac4461118453cd24c7a5afe93/docs/docs/configuration/server.rst#guard

Quote:
> `reply-to-self`
>    allow commenters to reply to their own comments when they could still edit the comment. After the editing timeframe is gone, commenters can reply to their own comments anyways.
>    Do not forget to configure the client accordingly

This setting defaults to false to prevent people from having conversations with themselves where it makes more sense to edit your comment instead. Change the setting in your config to true if you wish to allow replying to yourself.

By `Browser #2` I assume you mean (a different device) with a different IP address? Isso uses IP addresses to distinguish between different users, see https://github.com/posativ/isso/blob/e6dbd21819f8fdca9fdace447e9ba01276e8d6a9/isso/db/spam.py#L56-L67

Otherwise, I'd be a bit puzzled why just using another browser would allow you to circumvent the guard system.

---

> What info do you need? I think the steps to reproduce the issue are pretty clear. Please tell me what needs more clarification.

The label wasn't meant for you to supply more factual information, but rather to confirm your issue is still valid.
It's more of a way for maintainers to know which issues to look at. It wouldn't make sense to look at this issue again for us until you confirmed this is current.

**Comment by mdosch** [comment]
Am 31. Dezember 2021 16:52:20 UTC schrieb ix5 ***@***.***>:
>What you're looking at is a spam prevention measure by isso. See the explanation for the `[guard]` section in isso's documentation here:
>https://github.com/posativ/isso/blob/be538a2abbaa1e1ac4461118453cd24c7a5afe93/docs/docs/configuration/server.rst#guard
>
>Quote:
>> `reply-to-self`
>>    allow commenters to reply to their own comments when they could still edit the comment. After the editing timeframe is gone, commenters can reply to their own comments anyways.
>>    Do not forget to configure the client accordingly
>
>This setting defaults to false to prevent people from having conversations with themselves where it makes more sense to edit your comment instead. Change the setting in your config to true if you wish to allow replying to yourself.
>
>By `Browser #2` I assume you mean (a different device) with a different IP address? Isso uses IP addresses to distinguish between different users, see https://github.com/posativ/isso/blob/e6dbd21819f8fdca9fdace447e9ba01276e8d6a9/isso/db/spam.py#L56-L67
>
>Otherwise, I'd be a bit puzzled why just using another browser would allow you to circumvent the guard system.
>
>---
>
>> What info do you need? I think the steps to reproduce the issue are pretty clear. Please tell me what needs more clarification.
>
>The label wasn't meant for you to supply more factual information, but rather to confirm your issue is still valid.
>It's more of a way for maintainers to know which issues to look at. It wouldn't make sense to look at this issue again for us until you confirmed this is current.
>

But then: Why can't you comment to others comments in that time? That monologue prevention should stop once there is another comment. The browser #2 was used to create a comment 'by another person'.

**Comment by mdosch** [comment]
Ah, OK. You use the IP. Will have to check with Torbrowser then. I only know one person complained he could not reply to a reply as long as he was still able to edit his first post.

**Comment by ix5** [comment]
> But then: Why can't you comment to others comments in that time? That monologue prevention should stop once there is another comment. The `browser #2` was used to create a comment 'by another person'.

Feel free to submit a Pull Request to change the current behaviour. I linked you to the `_limit` function where you can check whether a reply to the current parent already exists. Otherwise just lift the guard restrictions, either by shortening `max-age` or by allowing reply-to-self.

Note that Isso has no notion of comment nesting of more than 1 (i.e. it doesn't know about replies to replies, rather everything is either a top-level comment or a reply to a top-level-comment).
