### ISSUE TITLE
require-author needs to be set

### ISSUE THREAD

**Issue by Vipermaseg** [posativ/isso#344]
Using Isso pretty much out of the box throws an exception that complains about this:
configparser.NoOptionError: No option 'require-author' in section: 'guard'

When the option is added, at the time of starting Isso I get this other warning:
WARNING: no such option: [guard] require-author

But it seems to work fine.

The documentation says:
data-isso-require-author
Set to true when spam guard is configured with require-author = true.

So, afaik, that warning is misleading and defaults should include require-author. Tell me if I am wrong.

I'm using version 0.10.5 provided at the Arch AUR.

**Comment by ix5** [comment]
This must have been an issue with Isso 0.10.5, the provided default conf (from which default values are read if not overwritten by values from your own config) did not contain the `require-author` key and thus no default was written:
https://github.com/posativ/isso/blob/0.10.5/share/isso.conf

This issue has since been fixed.
