### ISSUE TITLE
isso/js/app/i18n/en.js in Docker wonderfall image?

### ISSUE THREAD

**Issue by rabas007** [posativ/isso#371]
I am trying to change the placeholder text in the commenting boxes, but I cannot find the above file in my Docker image. Where, how to make changes...

```
<script data-isso="https://isso.mydomain.com/" src="https://isso.mydomain.com/js/embed.min.js"></script>
<script data-isso="/prefix/" data-isso-css="false" data-isso-lang="en" data-isso-reply-to-self="true" data-isso-require-author="true"
    data-isso-require-email="true" data-isso-max-comments-top="3" data-isso-max-comments-nested="5" data-isso-reveal-on-click="2"
    data-isso-avatar="true" data-isso-avatar-bg="#f0f0f0" data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 ..." data-isso-vote="true"
    data-vote-levels="" src="/prefix/js/embed.js"></script>
```

**Comment by blatinier** [comment]
For the record, the DockerImage we speak of is this one: https://github.com/Wonderfall/docker-isso (some basic search skill give it, but direct link is no bad too)

Your DockerImage install isso through pip which only contains compiled versions of JS files in `/usr/local/lib/pythonX.X/site-packages/isso/js/` (or something like that).
From here you have 3 solutions:
- You can change your HTML code and use `embed.dev.js` instead of `embed.min.js`. The dev file is not minified so it's easily editable (but heavier…). Go around line 590 for English translations.
- If you are a bit more adventurous you could do some editing directly in the `embed.min.js` which is the result of the compilation. (around line 19 col 6910)
- Finally you can create your own DockerImage to install from git then modify the placeholder and then compile the JS (using the `Makefile`).

I hope it answers you question. Please advise us if it does so we can close (or answer more)

**Comment by rabas007** [comment]
Great! I try the adventurous route... :)
That will solve it, thanks a lot for your help!
