### ISSUE TITLE
Drop support for Python 2.6 and 3.3 which are both EOL?  

### ISSUE THREAD

**Issue by cclauss** [posativ/isso#379]
* Python 2.6 reached its [end of life](https://devguide.python.org/#branchstatus) in 2013.
* Python 3.3 reached its end of life in 2017.

**Comment by blatinier** [comment]
I don't know the code base really well but some grep with "26", "2.6" showed nothing but some deps management in the setup.py which not really a burden for the project. Unless I missed something I think we should keep it.
And it might be too soon for 3.3.

**Comment by jelmer** [comment]
+1 to what @blatinier said. If the 2.6 support gets in the way, it may be time to consider dropping it.

**Comment by cclauss** [comment]
1. Official Python Porting Guide: https://docs.python.org/3/howto/pyporting.html#drop-support-for-python-2-6-and-older
2. [Depreciation warning in recent isso build](https://travis-ci.org/posativ/isso/jobs/331310455#L495)
3. https://github.com/posativ/isso/issues/332

**Comment by blatinier** [comment]
Ok you got me when I saw the commit of @posativ dropping 2.6 support 3 years ago :) (even if it's not merged yet)

Is there specific code related to 3.3 support?

**Comment by hugovk** [comment]
Here's the pip installs for isso from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   62.6% |            114 |
| 3.6            |   20.3% |             37 |
| 3.5            |   14.3% |             26 |
| 2.6            |    1.6% |              3 |
| 3.4            |    1.1% |              2 |

Source: `pypinfo --start-date -55 --end-date -25 --percent --pip --markdown isso pyversion`

Very little 2.6 and nothing for 3.3.

I don't see any code that can be dropped because it's 3.3-specific (there's a much bigger benefit for ditching 2.6), but similarly, there's not much point keeping it either. One benefit is an extra Travis CI slot can be freed up. Another is if ever something does come up that breaks for 3.3, you won't ever need to be worried by it.
