### ISSUE TITLE
Number of comments as Integer

### ISSUE THREAD

**Issue by fabianbuettner** [posativ/isso#387]
Hey,

I would like to display the number of comments as number and not as word(just "1" instead of "One").
Any ideas on how to achieve that?

regards,
Fabian

**Comment by blatinier** [comment]
This is handled in the translation files. (`isso/js/app/i18n/en.js`)

If you build isso yourself from source, find the `en.js` file and change `One` into `1` and then rebuild the js.
If you installed isso through pip you must find the `embed.min.js` file and replace the `One` by `1` in this file. You can also modify the `embed.dev.js` which is easier to manipulate and you this `dev` file in your app instead of the `min` one.

**Comment by fabianbuettner** [comment]
Thank you :)
