### ISSUE TITLE
UTF-8 is not broken !

### ISSUE THREAD

**Issue by 22decembre** [posativ/isso#502]
When I run isso on OpenBSD, I got that error :

```
/var/www/isso/lib/python3.6/site-packages/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
  BrokenFilesystemWarning)
```

UTF-8 is not broken. It is the actual (modern, up to date) encoding system !

**Comment by jelmer** [comment]
Note that the BrokenFilesystemWarning is complaining about the filesystem encoding being /ascii/; it'll use UTF-8 instead of that.

This warning is being raised by werkzeug, one of the libraries used by isso, rather than by isso itself. If you think it should be doing something different (rather than UTF-8), it's probably best to file a bug against werkzeug.

**Comment by 22decembre** [comment]
I am saying that werkzeug should not complain for using UTF8 : it is the good behavior.

It should complain if NOT being able to use UTF8, as UTF8 is now the de-facto modern standard.

**Comment by jelmer** [comment]
It's complaining that your settings suggest you're using ASCII on your filesystem, but that it will use UTF-8 instead.

**Comment by 22decembre** [comment]
Good boy.

Thanks
