### ISSUE TITLE
UNABLE TO SAVE COMMENTS TO SQLITE DATABASE

### ISSUE THREAD

**Issue by mikemainz** [posativ/isso#561]
Hello.

Am beyond my wits and need assistance in resolving issue logged below:

pcre jit disabled
detected number of CPU cores: 1
current working directory: /
detected binary path: /opt/django/vbaraza/vbaraza/bin/uwsgi
chdir() to /opt/django/vbaraza
your processes number limit is 3843
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "hash" initialized: 2MB (key: 2136 bytes, keys: 2187264 bytes, data: 32768 bytes, bitmap: 0 bytes) preallocated ***
uwsgi socket 0 bound to UNIX address /run/uwsgi/vbaraza.sock fd 4
setuid() to 997
Python version: 3.6.3 (default, Mar 20 2018, 13:50:41)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Set PythonHome to /opt/django/vbaraza/vbaraza
Python main interpreter initialized at 0x1b889c0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores

*** Operational MODE: preforking ***
2019-07-26 07:02:13,755 INFO: connected to SMTP server
2019-07-26 07:02:13,808 INFO: connected to https://blog.mydomain.com/
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1b889c0 pid: 19065 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19065)
spawned the uWSGI spooler on dir /opt/django/vbaraza/data/spool with pid 19070
spawned uWSGI worker 1 (pid: 19071, cores: 1)
spawned uWSGI worker 2 (pid: 19072, cores: 1)
cache sweeper thread enabled
[pid: 19071|app: 0|req: 1/1] xyz.xyz.xyz.xyz () {48 vars in 778 bytes} [Fri Jul 26 07:02:18 2019] OPTIONS /preview => generated 0 bytes in 1 msecs (HTTP/2.0 200) 6 headers in 323 bytes (0 switches on core 0)
[pid: 19072|app: 0|req: 1/2] xyz.xyz.xyz.xyz () {50 vars in 1238 bytes} [Fri Jul 26 07:02:18 2019] POST /preview => generated 154 bytes in 29msecs (HTTP/2.0 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 19071|app: 0|req: 2/3] xyz.xyz.xyz.xyz () {48 vars in 803 bytes} [Fri Jul 26 07:02:21 2019] OPTIONS /new?uri=%2Fsearch%2F => generated 0 bytes in 0 msecs (HTTP/2.0 200) 6 headers in 323 bytes (0 switches on core 0)
2019-07-26 07:02:21,292 ERROR: POST /new
Traceback (most recent call last):
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/__init__.py", line 141, in dispatch
    response = handler(request.environ, request, **values)
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/comments.py", line 92, in dec
    return func(self, env, req, *args, **kwargs)
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/__init__.py", line 46, in dec
    return func(cls, env, req, *args, **kwargs)
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/comments.py", line 282, in new
    thread = self.threads.new(uri, title)
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/db/threads.py", line 33, in new
    "INSERT INTO threads (uri, title) VALUES (?, ?)", (uri, title))
  File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/db/__init__.py", line 62, in execute
    return con.execute(sql, args)
sqlite3.OperationalError: unable to open database file
[pid: 19071|app: 0|req: 3/4] xyz.xyz.xyz.xyz () {50 vars in 1263 bytes} [Fri Jul 26 07:02:21 2019] POST /new?uri=%2Fsearch%2F => generated 290 bytes in 6 msecs (HTTP/2.0 500) 7 headers in 362 bytes (1 switches on core 0)

**Comment by blatinier** [comment]
You have a permission issue when opening database file. check the path of your db and folder permissionsEnvoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : mikemainz <notifications@github.com> 
Date : 26/07/2019  14:06  (GMT+07:00) 
À : posativ/isso <isso@noreply.github.com> 
Cc : Subscribed <subscribed@noreply.github.com> 
Objet : [posativ/isso] UNABLE TO SAVE COMMENTS TO SQLITE DATABASE (#561) 

Hello.
Am beyond my wits and need assistance in resolving issue logged below:
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
detected binary path: /opt/django/vbaraza/vbaraza/bin/uwsgi
chdir() to /opt/django/vbaraza
your processes number limit is 3843
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "hash" initialized: 2MB (key: 2136 bytes, keys: 2187264 bytes, data: 32768 bytes, bitmap: 0 bytes) preallocated ***
uwsgi socket 0 bound to UNIX address /run/uwsgi/vbaraza.sock fd 4
setuid() to 997
Python version: 3.6.3 (default, Mar 20 2018, 13:50:41)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Set PythonHome to /opt/django/vbaraza/vbaraza
Python main interpreter initialized at 0x1b889c0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
2019-07-26 07:02:13,755 INFO: connected to SMTP server
2019-07-26 07:02:13,808 INFO: connected to https://blog.mydomain.com/
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1b889c0 pid: 19065 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19065)
spawned the uWSGI spooler on dir /opt/django/vbaraza/data/spool with pid 19070
spawned uWSGI worker 1 (pid: 19071, cores: 1)
spawned uWSGI worker 2 (pid: 19072, cores: 1)
cache sweeper thread enabled
[pid: 19071|app: 0|req: 1/1] xyz.xyz.xyz.xyz () {48 vars in 778 bytes} [Fri Jul 26 07:02:18 2019] OPTIONS /preview => generated 0 bytes in 1 msecs (HTTP/2.0 200) 6 headers in 323 bytes (0 switches on core 0)
[pid: 19072|app: 0|req: 1/2] xyz.xyz.xyz.xyz () {50 vars in 1238 bytes} [Fri Jul 26 07:02:18 2019] POST /preview => generated 154 bytes in 29msecs (HTTP/2.0 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 19071|app: 0|req: 2/3] xyz.xyz.xyz.xyz () {48 vars in 803 bytes} [Fri Jul 26 07:02:21 2019] OPTIONS /new?uri=%2Fsearch%2F => generated 0 bytes in 0 msecs (HTTP/2.0 200) 6 headers in 323 bytes (0 switches on core 0)
2019-07-26 07:02:21,292 ERROR: POST /new
Traceback (most recent call last):
File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/init.py", line 141, in dispatch
response = handler(request.environ, request, **values)
File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/comments.py", line 92, in dec
return func(self, env, req, *args, **kwargs)
File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/init.py", line 46, in dec
return func(cls, env, req, *args, **kwargs)
File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/comments.py", line 282, in new
thread = self.threads.new(uri, title)
File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/db/threads.py", line 33, in new
"INSERT INTO threads (uri, title) VALUES (?, ?)", (uri, title))
File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/db/init.py", line 62, in execute
return con.execute(sql, args)
sqlite3.OperationalError: unable to open database file
[pid: 19071|app: 0|req: 3/4] xyz.xyz.xyz.xyz () {50 vars in 1263 bytes} [Fri Jul 26 07:02:21 2019] POST /new?uri=%2Fsearch%2F => generated 290 bytes in 6 msecs (HTTP/2.0 500) 7 headers in 362 bytes (1 switches on core 0)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/posativ/isso/issues/561?email_source=notifications\u0026email_token=AAIJJJIJAFKWIM5JUMHKCB3QBKO6DA5CNFSM4IHBCJH2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBUTTXA",
"url": "https://github.com/posativ/isso/issues/561?email_source=notifications\u0026email_token=AAIJJJIJAFKWIM5JUMHKCB3QBKO6DA5CNFSM4IHBCJH2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBUTTXA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mikemainz** [comment]
Hello,




Who should own the database root / isso / or uwsgi?




When I delete the database comments.db I can pick up error in my log file but after recreating it the application starts without much of an issue, problem comes in during write process.








Get Outlook for Android







On Fri, Jul 26, 2019 at 11:25 AM +0300, "Benoit Latinier" <notifications@github.com> wrote:













    


You have a permission issue when opening database file. check the path of your db and folder permissionsEnvoyé depuis mon appareil Samsung





-------- Message d'origine --------


De : mikemainz <notifications@github.com> 


Date : 26/07/2019  14:06  (GMT+07:00) 


À : posativ/isso <isso@noreply.github.com> 


Cc : Subscribed <subscribed@noreply.github.com> 


Objet : [posativ/isso] UNABLE TO SAVE COMMENTS TO SQLITE DATABASE (#561) 





Hello.


Am beyond my wits and need assistance in resolving issue logged below:


pcre jit disabled


detected number of CPU cores: 1


current working directory: /


detected binary path: /opt/django/vbaraza/vbaraza/bin/uwsgi


chdir() to /opt/django/vbaraza


your processes number limit is 3843


your memory page size is 4096 bytes


detected max file descriptor number: 1024


lock engine: pthread robust mutexes


thunder lock: disabled (you can enable it with --thunder-lock)


*** Cache "hash" initialized: 2MB (key: 2136 bytes, keys: 2187264 bytes, data: 32768 bytes, bitmap: 0 bytes) preallocated ***


uwsgi socket 0 bound to UNIX address /run/uwsgi/vbaraza.sock fd 4


setuid() to 997


Python version: 3.6.3 (default, Mar 20 2018, 13:50:41)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]


Set PythonHome to /opt/django/vbaraza/vbaraza


Python main interpreter initialized at 0x1b889c0


python threads support enabled


your server socket listen backlog is limited to 100 connections


your mercy for graceful operations on workers is 60 seconds


mapped 218760 bytes (213 KB) for 2 cores


*** Operational MODE: preforking ***


2019-07-26 07:02:13,755 INFO: connected to SMTP server


2019-07-26 07:02:13,808 INFO: connected to https://blog.mydomain.com/


WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1b889c0 pid: 19065 (default app)


*** uWSGI is running in multiple interpreter mode ***


spawned uWSGI master process (pid: 19065)


spawned the uWSGI spooler on dir /opt/django/vbaraza/data/spool with pid 19070


spawned uWSGI worker 1 (pid: 19071, cores: 1)


spawned uWSGI worker 2 (pid: 19072, cores: 1)


cache sweeper thread enabled


[pid: 19071|app: 0|req: 1/1] xyz.xyz.xyz.xyz () {48 vars in 778 bytes} [Fri Jul 26 07:02:18 2019] OPTIONS /preview => generated 0 bytes in 1 msecs (HTTP/2.0 200) 6 headers in 323 bytes (0 switches on core 0)


[pid: 19072|app: 0|req: 1/2] xyz.xyz.xyz.xyz () {50 vars in 1238 bytes} [Fri Jul 26 07:02:18 2019] POST /preview => generated 154 bytes in 29msecs (HTTP/2.0 200) 7 headers in 350 bytes (1 switches on core 0)


[pid: 19071|app: 0|req: 2/3] xyz.xyz.xyz.xyz () {48 vars in 803 bytes} [Fri Jul 26 07:02:21 2019] OPTIONS /new?uri=%2Fsearch%2F => generated 0 bytes in 0 msecs (HTTP/2.0 200) 6 headers in 323 bytes (0 switches on core 0)


2019-07-26 07:02:21,292 ERROR: POST /new


Traceback (most recent call last):


File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/init.py", line 141, in dispatch


response = handler(request.environ, request, **values)


File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/comments.py", line 92, in dec


return func(self, env, req, *args, **kwargs)


File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/init.py", line 46, in dec


return func(cls, env, req, *args, **kwargs)


File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/views/comments.py", line 282, in new


thread = self.threads.new(uri, title)


File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/db/threads.py", line 33, in new


"INSERT INTO threads (uri, title) VALUES (?, ?)", (uri, title))


File "/opt/django/vbaraza/vbaraza/lib/python3.6/site-packages/isso/db/init.py", line 62, in execute


return con.execute(sql, args)


sqlite3.OperationalError: unable to open database file


[pid: 19071|app: 0|req: 3/4] xyz.xyz.xyz.xyz () {50 vars in 1263 bytes} [Fri Jul 26 07:02:21 2019] POST /new?uri=%2Fsearch%2F => generated 290 bytes in 6 msecs (HTTP/2.0 500) 7 headers in 362 bytes (1 switches on core 0)





—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


[


{


"@context": "http://schema.org",


"@type": "EmailMessage",


"potentialAction": {


"@type": "ViewAction",


"target": "https://github.com/posativ/isso/issues/561?email_source=notifications\u0026email_token=AAIJJJIJAFKWIM5JUMHKCB3QBKO6DA5CNFSM4IHBCJH2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBUTTXA",


"url": "https://github.com/posativ/isso/issues/561?email_source=notifications\u0026email_token=AAIJJJIJAFKWIM5JUMHKCB3QBKO6DA5CNFSM4IHBCJH2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBUTTXA",


"name": "View Issue"


},


"description": "View this Issue on GitHub",


"publisher": {


"@type": "Organization",


"name": "GitHub",


"url": "https://github.com"


}


}


]
