### ISSUE TITLE
Useful CLI tool to display comments grouped by replies

### ISSUE THREAD

**Issue by Lucas-C** [posativ/isso#634]
Hi !

I use isso on my blog, and I like it very much !
I added support for it to my Pelican theme : https://github.com/Lucas-C/pelican-mg#features
Sincere thanks for developping it, and releasing it as open source software :)

Today I made a short script to display isso comments in my terminal :
https://github.com/Lucas-C/dotfiles_and_notes/blob/master/languages/python/isso_dump_comments.py

Preview:
![2020-04-15 16_14_36-tmux_lucas_cimon_1_ tmux  -](https://user-images.githubusercontent.com/925560/79347932-93a03b00-7f34-11ea-8434-ee6586be2aec.png)

It's really not much, but I though I'd share it here.
Is there a place to share isso-related tools ?
If ever you want to adopt it, please feel free to add it to any isso repo (in `bin/` maybe ?).

Regards

**Comment by jelmer** [comment]
Hi Lucas,

Thanks, that looks like a useful tool.

Can you add a copyright + license header (like exists in isso/__init__.py), so that it's clear that we can include it in the main isso repository?

There is a contrib/ directory in isso that I think this could live in as well. A pull request adding the script with the copyright/license header in contrib/ would be awesome. Otherwise, please ping me once you've added the header and I can add it.

Jelmer

**Comment by Lucas-C** [comment]
Working on it !

A couple of questions :
- is there a place in the docs where to mention it ?
- do you need unit tests for this ?

**Comment by jelmer** [comment]
Unit tests would be awesome, but I'd be happy to merge this into contrib/ even without them. I don't believe we have unit tests for any command-line interfaces yet in isso, so you'd be a bit on your own there.

I think the documentation lacks any details on the admin section altogether at the moment, but that's probably where I would mention it.

**Comment by Lucas-C** [comment]
Alright. I'm going to add something in the doc but skip the tests for now, as it does not look quick & easy to generate an `isso.db` test file for them
