### ISSUE TITLE
Could a new release be made?

### ISSUE THREAD

**Issue by fluffy-critter** [posativ/isso#678]
There's been a lot of changes in isso since the last release (0.12.2) which was two years ago, many of which are important bugfixes such as #599. Could there be a new release made so that people don't have to build it themselves, especially with how difficult the build is to get set up?

Thanks!

**Comment by cmoetzing** [comment]
I basically agree, but building is fairly simple if you use docker. Dockerfile is already provided.

**Comment by fluffy-critter** [comment]
Isso's installation instructions say to use pypi as the primary source, and also I have run into trouble with Docker in the past and don't want to pollute my VPS with it so I'd rather not go that route.

**Comment by Fryboyter** [comment]
> I basically agree, but building is fairly simple if you use docker. Dockerfile is already provided.

But not everyone can use Docker. For example, I use uberspace.de as my webspace provider. There you have significantly more rights than with a normal webspace, but not enough for things like Docker.

I therefore use the installation via pip install isso. However, this type of installation does not work smoothly due to https://github.com/posativ/isso/issues/617. At least that was the case a few weeks ago.

**Comment by ix5** [comment]
The maintainers just released [0.12.4](https://pypi.org/project/isso/0.12.4/) and are very responsive to well-written PRs.
Thanks, @jelmer and @blatinier !

I think this can be closed.
