### ISSUE TITLE
[Discussion][Multi-Site] Future of cookies with SameSite and Secure

### ISSUE THREAD

**Issue by ix5** [posativ/isso#682]
As of 2021-01, Firefox 84 warns when hosting isso on a subdomain and accessing cookies.

Repro:
- Isso hosted at `comments.example.com`
- "Blog" hosted at `example.com`

**Warning:**
```
Cookie “isso-[id]” will be soon rejected because it has the “SameSite” attribute set to “None”. [...]
```
with a link to [MDM SameSite cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite).

**Cause:**  
In [isso/views/comments.py](https://github.com/posativ/isso/blob/944e4846847abc9b252f9b016158e336ffb77443/isso/views/comments.py#L312-L333), e.g. `new()` creates a new cookie with `SameSite` implicitly set to `False` and `Secure` implicitly set to `None`[^1].

**Possible solutions**  
1. Isso sets `Secure` cookie by default. Big problem is that large parts of isso    assume that it might be accessed over `http`, see e.g. the    [default isso.conf](https://github.com/posativ/isso/blob/944e4846847abc9b252f9b016158e336ffb77443/share/isso.conf#L23-L27)
2. Isso conditionally sets `Secure` cookie only for `https` hosts. Ugly but    doable.

**Help wanted**  
Would be great if someone who's more involved with web technology could step in and give their ideas and clarify whether my understanding here is even correct.

[^1]: For the full call chain, see the later [X-Set-Cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) and the defaults of `werkzeug`'s [http.dump_cookie](https://werkzeug.palletsprojects.com/en/1.0.x/http/#werkzeug.http.dump_cookie)

**Comment by Fryboyter** [comment]
> Big problem is that large parts of isso assume that it might be accessed over http, see e.g. the default isso.conf

According to the documentation, the entry for host with http only exists because of Firefox users who completely suppress the HTTP referer. As far as I know, this must be configured explicitly via about:config.

In my configuration, the entries were previously in reverse order. So first https and then http. There have been no complaints so far. I just tested it and completely removed the http entry from the configuration file. Isso continued to work with Firefox without any problems.

Thanks to Let's Encrypt, more and more pages are only accessible via https. So if the http entry is the only problem (I'm not an expert on SameSite etc.) then I would risk locking out these users in the worst case. Just like users who don't activate Javascript can't use Isso either.

**Comment by ix5** [comment]
That's my current solution https://github.com/ix5/isso/tree/secure-cookie

**Comment by stefangehn** [comment]
Since isso can probably not figure out if it's only served over https (and not http) maybe a config option would be the easiest way out, at least for the `Secure` setting.

For comparison, Gitea has a `COOKIE_SECURE` setting in its [session config](https://docs.gitea.io/en-us/config-cheat-sheet/#session-session) that controls this.

**Comment by ix5** [comment]
I'm wary of adding yet another config option that users have to think about. We should be able to re-use the [`public-endpoint`](https://github.com/posativ/isso/blob/af26e201f81d3106036c7302d38ea24c2e203977/share/isso.conf#L105) from the `[server]` section.

**Comment by stefangehn** [comment]
If that works reliable then I would of course also prefer to have no additional options :)

I was just thinking about all the different ways how you can proxy a webapp these days and the (possibly) varying amount of information forwarded to the app (for nginx you usually need to ensure to include `uwsgi_params` or `proxy_params` to get a complete set of variables and many examples instead just define a small subset of them, leading to odd results).
