### ISSUE TITLE
Isso - How to replace Disqus on Wordpress?

### ISSUE THREAD

**Issue by yeehi** [posativ/isso#701]
Many people may have had Disqus installed by default on their Wordpress website.  
https://wordpress.org/plugins/disqus-comment-system/  

Is there an easy (one click) way to remove Disqus and replace it with Isso?  
  
I think an Isso plugin for Wordpress might encourage more widespread usage.

**Comment by ix5** [comment]
Adding custom javascript to wordpress is already quite well documented.

There definitely isn't a one-click solution as isso is by design self-hosted. I am not aware of anyone providing public isso instances for everyone to use (not sure that's currently even feasible, with CORS and whatnot - and in any case, that'd be a nightmare to administer).

An wordpress plugin for isso couldn't do very much apart from maybe providing a GUI to configuring the `data-isso` attributes of the script.

**Comment by 4044ever** [comment]
I am late, when I understand you correctly you want to remove Disqus and use isso. So you need to:

1. Export your comments from Disqus as XML
2. Import the XML to isso
3. then simply disable and remove Disqus from Wordpress
4. Put the isso page/client script to WP (best in footer)

This link may help:
https://stiobhart.net/2017-02-24-isso-comments/#_disqus_com_export_existing_comments_from_disqus_as_xml
