### ISSUE TITLE
dependency jade should be replaced

### ISSUE THREAD

**Issue by stbuehler** [posativ/isso#725]
Hi,

I just took a look at [debian bug #959644: isso: FTBFS: TypeError: Jade:1](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959644), and the conclusion is that `node-jade` in debian bullseye is [completely broken](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987967) due to incompatibilities with newer versions of its dependencies, and I don't see it getting fixed given its quite old.

It'd be really nice if isso could use more up-to-date dependencies, in which case I'd have some hope for isso making it into bullseye backports (bullseye release seems quite unlikely).

**Comment by stefangehn** [comment]
Since the successor "pug" does not appear to be packaged in Debian I don't think there's anything that can help with the Debian package in the short run.

I can probably look into porting isso to pug but I'm not exactly fluent in JavaScript (and don't like it either), I'm more at home with Python.

For now I would recommend to install isso via pip (and into a virtualenv) instead.

**Comment by stbuehler** [comment]
Yes, there will be challenges ahead (not a javascript fanboy myself either). But I think `pug` has a better chance to be properly maintained in debian than `jade`. I'm not sure how important `jade` is in `isso` anyway - perhaps it can be made optional if it's just for generating docs?

The python dependencies are not a problem (yet), so no virtualenv needed; I don't see how virtualenv would solve the javascript problems.

My current plan is going for the docker image or looking for new alternatives to isso.

**Comment by stefangehn** [comment]
Installing from pypi via pip (either with our without a virtualenv) will contain prebuilt files so Jade is at least not an issue for you as a user. AFAIK Jade is used for html templating in the JS code, i.e. it is the logic that renders comments as HTML inside the browser.

**Comment by blatinier** [comment]
Globally the JS is quite old (that's an understatment). 
It could benefit a full refactor using either vanillaJS, like here with some lib imported or maybe some "micro framework" like preact, svelte, ...

**Comment by ix5** [comment]
The debian package has been discontinued according to jelmer in https://github.com/posativ/isso/discussions/774#discussioncomment-2153559

Since no one seemed to want to tackle the issue, I decided to move forward with a webpack port, which dropped `jade` (and associated hacks/shims) in favor of `pug`.

I've assigned this to milestone 0.13 since a major reworking of the way the client is assembled should permit us to revisit dependencies as well.

**Comment by ix5** [comment]
https://github.com/posativ/isso/pull/800 moved Isso's client templating engine to `pug`. Closing.
