### ISSUE TITLE
"Hidden" and "Staled" posts in the admin area. What do they mean?

### ISSUE THREAD

**Issue by gravelld** [posativ/isso#730]
Following an import of about 2k posts from Disqus, I can see eight of them are in the _Staled_ section of the admin page.

What does _Staled_ mean?

They are marked **HIDDEN**. How do I unhide them... but more importantly why are they hidden in the first place?

**Comment by ix5** [comment]
That's a bit of unfortunate behavior in the migrate function:

https://github.com/posativ/isso/blob/a7c1069cf5feab721a166e7796ce725287a46189/isso/migrate.py#L115

While importing from Disqus, isso sets the `mode` of a comment based on whether the `isDeleted` field in the exported Disqus database is explicitly set to `false`. I'm guessing that Disqus has some sort of soft-delete function which isso tries to honor.

Isso is being overly cautious and defaults to not showing ("staling") a comment if the `isDeleted` field is *not* set to `false` - perhaps in order to prevent inadvertently showing imported hidden comments if Disqus' database schema should change.

Explanation of comment `mode`:

https://github.com/posativ/isso/blob/a7c1069cf5feab721a166e7796ce725287a46189/isso/db/comments.py#L29-L30

A stale comment with no children will be removed by a database trigger, btw.

---

**As for your dilemma:**
You can edit your database (back it up first, of course) and convert all stale comments to pending ones. Then you can manually approve (unhide) or delete each comment in the admin interface.

SQL (YMMV, not tested this myself): `UPDATE comments SET mode=2 WHERE mode=4`

Or just "approve" all stale comments: `UPDATE comments SET mode=1 WHERE mode=4`

**Comment by ix5** [comment]
@gravelld if your issue has been solved, would you mind closing it? Or do you have further questions?

**Comment by gravelld** [comment]
Yes, I haven't had the chance to update the database, but it looks like this should be fine when/if I get to it. Apologies for not following up earlier.
