### ISSUE TITLE
Problem with CORS - multiple sites support is broken

### ISSUE THREAD

**Issue by vsajip** [posativ/isso#735]
Multiple site support is broken because you can't specify host-dependent CORS headers. I have two sites `https://comments.foo.com/`, `https://comments.bar.com/` for comments on sites `https://blog.foo.com/` and `https://blog.bar.com/` respectively. What I need is to send a CORS header corresponding to the appropriate site the comment site is for, but there's no way of doing this, from what I can tell.

As a quick hack for testing, I modified the `origin()` function in `isso/wsgi.py` to return `https://blog.foo.com` when a request comes in to `https://comments.foo.com` and to return `https://blog.bar.com` when the request comes in to `https://comments.bar.com`, and that works as expected for both sites. However, that *is* only a temporary hack. The correct solution is to have a configured mapping between the host and the origin which Isso picks up and uses automatically. For example, by accepting and using a `cors_origin` key in the configuration for each site.

**Comment by thomasjsn** [comment]
You solve it with `proxy_set_header` in the Nginx location block. And have separate server blocks for the two sites. If you are using Nginx as a proxy in front of Isso.

**Comment by vsajip** [comment]
No doubt, but that's sub-optimal compared to ISSO being configurable to do the right thing.

**Comment by ix5** [comment]
Possibly related: https://github.com/posativ/isso/issues/720, https://github.com/posativ/isso/issues/558

PRs welcome.

**Comment by ix5** [comment]
As I tried to explain in https://github.com/posativ/isso/issues/720#issuecomment-1049162444, please set the correct headers in your proxying server.
The docs should be updated to reflect this necessity, but I am afraid I can not accomodate your wishes.

**Comment by vsajip** [comment]
> please set the correct headers in your proxying server

The sites I'm working with are in a shared hosting environment, not a VPS. I don't have control over the proxy server configuration. With reference to your comment in #720, I'm in option (b) but with no way to set headers. How do you suggest I resolve this?

**Comment by ix5** [comment]
I can see your point. While your case is valid, my opinion remains that adding more handling for edge cases will not serve us in the long run.

The same root problem - Isso's notion of multiple-sites setup using multiple Isso instances - will bite us again and again.

https://github.com/posativ/isso/issues/647 and https://github.com/posativ/isso/issues/566 are related as well. Ideally, Isso would only have one instance that is aware of all underlying managed sites. Let's push in that direction (using full URIs) instead of trying introduce some kind of origin->site->host mapping syntax to Isso's config.

Oh, and another point to make: Even if that kind of syntax were to be introduced, the only people in need of it would be other users of shared hosting (or unable to change proxy settings). Users of shared hosting tend to be either money-constrained, or, more often, novices to computing in general. Asking them to figure out the concept of Isso's virtual hosts and what maps to what will be challenging, to say the least. I'd wager you are the exception in terms of knowledge required.

**Comment by vsajip** [comment]
> Ideally, Isso would only have one instance that is aware of all underlying managed sites.

Yes, this would be a better direction to move in.
