### ISSUE TITLE
"in reply to" feature is missing

### ISSUE THREAD

**Issue by gregoriy96** [posativ/isso#746]
I noticed that there was no information about who I replied to.

It should look something like this:
![Снимок экрана 2021-10-07 0100064234](https://user-images.githubusercontent.com/29800587/136450900-db261b8f-f1a7-49d3-9845-1730c81a78f8.jpg)

Would also be great to see if a comment was voted.

**Comment by ix5** [comment]
Hey @gregoriy96, that's a nice mockup, but by indenting the replies one level, it is already quite clear what a comment is referring to imo.

As such, your request isn't a missing feature in my eyes. If you want this implemented, you will need to step up and code this yourself (unless someone shares your sentiment).

As you can see, the issue tracker is already severely overloaded by trivial requests and people unwilling to read documentation/unwilling to solve their own issues and even valid Pull Requests linger in limbo because nobody has time to review/merge them.
