### ISSUE TITLE
configparser.InterpolationSyntaxError: for SMTP password

### ISSUE THREAD

**Issue by Aerya** [posativ/isso#763]
Hi,

How to allow Isso to parse pwds correctly?
`configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%!...@c...!Cjq'`

**Comment by ix5** [comment]
That's an interesting bug you have found in Isso. Thanks for reporting it!

The issue is that the [`configparser.ConfigParser`](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser) from Python that Isso uses tries to "interpret" (=interpolate) any string containing the `%` symbol using standard python string interpolation.

```
$ python3
>>> passwd = 'mysecretpw%s'
>>> passwd % 'hidden'
'mysecretpwhidden'
>>> passwd = 'mysecretpw%(mystr)s'
>>> passwd % {'mystr': 'hidden'}
'mysecretpwhidden'
```

The solution for you is to (temporarily) stop using passwords that contain `%` (or use `%%` in the config, `%` in the web interface). The next version of Isso should have this fixed.

**Comment by Aerya** [comment]
Thanks for incoming patch. I'll wait for it, I won't use less secure pwds.
