### ISSUE TITLE
Text not aligned: "No new message" etc

### ISSUE THREAD

**Issue by Aerya** [posativ/isso#766]
Hi,

I use Isso (your Docker) with Ghostblog and [Liebling theme](https://github.com/eddiesigner/liebling).
Some text is not aligned, CSS don't apply to it.

![](https://i.imgur.com/5m0zTJJ.png)
https://upandclear.org/on-la-refait/

Here's my client conf
```
<section class="post-full-comments">
    <script
      data-isso="https://isso.upandclear.org/"
      data-isso-css="true"
      data-isso-lang="fr"
      data-isso-vote="true"
      data-isso-reply-to-self="false"
      data-isso-require-author="true"
      data-isso-require-email="true"
      data-isso-reply-notifications="true"
      data-isso-max-comments-top="10"
      data-isso-max-comments-nested="5"
      data-isso-reveal-on-click="5"
      data-isso-gravatar="true"
      data-isso-avatar="false"
      src="//isso.upandclear.org/js/embed.min.js"></script>
<section id="isso-thread"></section>
```

Problem is as I use Docker I don't want to edit files in it (this text seems to be useless to me anyway). Any advice?

**Comment by ix5** [comment]
I am guessing you want to apply styles to the `<h4>` element that displays "No comments so far" in French?

The selector `#isso-thread > h4` should be all you need. I see you hid the element with an inline style definition as such:
```html
<style>
#isso-thread h4 { display:none !important;}
</style>
```

You could simply do the following:
```css
#isso-thread > h4 {
    text-align: center;
    color: blue;
    /* ... */
}
```

Or are you trying to make the `<h4>` element align horizontally with the post box below it?

Then you should wrap the whole isso area inside a container which is `68em` wide.
(See [isso.css](https://github.com/posativ/isso/blob/48a473606e20ec2afd139858164fc5550a0375dc/isso/css/isso.css#L160), the common width for `.isso-postbox` is 68em)

Alternatively, you could do the following:
```css
section.isso-thread {
    max-width: 68em !important;
    margin: 0 auto;
}
```
(`!important` shouldn't be needed since `section.isso-thread` is already more specific than just `.isso-thread`, thus taking precedence over definition in vendored `isso.css`)

Please note that this isn't really a bug for the issue tracker, rather a misunderstanding of how to write CSS on your part.

Closing as such, but feel free to re-open if this somehow really is a bug in isso which you would like addressed, ideally with a corresponding PR.

**Comment by Aerya** [comment]
Hi,

Yeah was talking about "Aucun commentaire pour l'instant". This should be centered by default. Thus I already hide it using code injections as you say
```
<style>
#isso-thread h4 { display:none !important;}
</style>
```
Isso includes a CSS option that centers the comment block, so it seemed logical to me that this text should be too since it depends on it and is almost stuck to it.

Nevermind, thanks for the good work anyway.

**Comment by ix5** [comment]
For future reference, we've enabled GitHub Discussions (over [here](https://github.com/posativ/isso/discussions)) to have a more suitable place for these kinds of questions/requests.

Feel free to try it out!
