### ISSUE TITLE
Postbox now appended after the comments

### ISSUE THREAD

**Issue by Kerumen** [posativ/isso#815]
Since [this PR](https://github.com/posativ/isso/commit/02f3ea0658680ce200258bc66d509403846b62d5#diff-cb455ab6a8d6bffcff6c41ffa6e2d8085369a4c3efbc5dbb49b738fe7f77ea01R73), the postbox is now appended after all the comments which is a bit annoying if you have a lot of comments. It was better to append it _before_ the `isso-root` (`<div id="isso-root"></div>`) to enable easy commenting from the users.

**Comment by adroste** [comment]
Same here. Super annoying.

**Comment by Kerumen** [comment]
CSS workaround:

```
#isso-thread {
  display: flex;
  flex-direction: column;
}

#isso-thread h4 {
  order: 1;
}

#isso-thread .isso-postbox {
  order: 2;
  width: 100%;
}

#isso-thread #isso-root {
  order: 3;
}
```

**Comment by ix5** [comment]
Thank you for reporting this issue. I have tagged [0.12.6.1](https://github.com/posativ/isso/commits/0.12.6.1) and uploaded a hotfix release to PyPi.

While I'm glad this regression was reported, it would have been better for all parties involved if someone had [tested and reported](https://github.com/posativ/isso/issues/806) this issue _before_ release.

I've pushed a PR of the fix as https://github.com/posativ/isso/pull/820, but we should revisit the way the client code constructs the core postbox and comment elements since we're now much more dependent on the calls to fetch config from the server before rendering anything.
[This piece of documentation](https://github.com/posativ/isso/blob/13b8df02c96392db1195db2e713e6f47b06dcd7e/docs/docs/extras/advanced-integration.rst#asynchronous-comments-loading) is also no longer 100% accurate.
