### ISSUE TITLE
pt_BR override translation not working

### ISSUE THREAD

**Issue by sol2070** [posativ/isso#982]
## Checklist
- [x] I am running the latest version. Installing Isso from GitHub from the `master` branch does not fix my issue
- [x] I have checked the [troubleshooting guide](https://isso-comments.de/docs/guides/troubleshooting/)
- [x] I have searched the [open issues](https://github.com/posativ/isso/issues), but my issue has not already been reported

## What is not working?

Overriding translation string for pt_BR (brazilian portuguese) is ignored. This is specific to this language. When I change to `en`, it works.

## How can one reproduce this issue?
It didn't work from the beginning, in an Ubuntu Server 20.04, Python 3.8.10, pip 20.0.2.

My script tag:

```
<script
  data-isso="https://isso.sol2070.in/"
  src="https://isso.sol2070.in/js/embed.min.js"
  data-isso-lang="pt_BR"
  data-isso-reply-notifications-default-enabled="true"
  data-isso-page-author-hashes="(redacted)"
  data-isso-postbox-text-text-pt_BR="Digite seu comentário. Markdown OK."
></script>
```

**Comment by ix5** [comment]
@sol2070 please give https://github.com/posativ/isso/pull/983 a try

**Comment by ix5** [comment]
> Thank you @ix5 ! Sorry, for some reason I did not receive the notification of the reply. Only saw now. I'm not sure how I can try these changes on my installation. Copying `config.js` and `i18n.js`?

The docs should help you here: [Install Isso from source](https://isso-comments.de/docs/reference/installation/#install-from-source)

In short, for only testing the updated Javascript file: `make init` and then `make js`, then drop the generated `embed.min.js` somewhere on your server or web directory/static files dir, then use that as the `<script src="/static/embed.min.js">` instead of pointing to `src="https://isso.sol2070.in/js/embed.min.js`

You can also grab the updated `embed.min.js` from the CI run https://github.com/posativ/isso/actions/runs/7587591176 (direct link: https://github.com/posativ/isso/actions/runs/7587591176/artifacts/1181755181 )
